### ISSUE TITLE
firegento.php and isDevAllowed?

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-debug#21]
Hey there,

the firegento.php is in the magento root. so everyone can open this file from remote.
So i think, the best way is to add the magento function

``` php
Mage::helper('core')->isDevAllowed()
```

so you can configure the allowed IPs in the magento Backend, or add an file support where u can set the access modes?

**Comment by arosenhagen** [comment]
:+1: this is a security issue in my eyes since the names of all installed extensions are exposed to the public. This should definitly be protected.

**Comment by mkutyba** [comment]
+1

**Comment by sreichel** [comment]
Is it planned to merge it into master branch?
